/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.quasar_x7.java.swing.stampa;

import javax.swing.JTextPane;



/**
 *
 * @author Ninja
 */
public class StampatoOrizzontale extends Stampato{
    
    private final StampatoController gestore;
    /**
     * Creates new form Stampato
     */
    public StampatoOrizzontale() {
        initComponents();
        this.gestore = new StampatoController(this);
        
    }
    
    @Override
    protected void aggiungiTesto(String testo) {
       gestore.aggiungiTesto(testo);
    }
    
    @Override
    public void cancella() {
        gestore.cancella();
    }
    
    @Override
    protected JTextPane areaTesto() {
        return this.areaTesto;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTesto = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));

        areaTesto.setBorder(null);
        areaTesto.setContentType("text/html"); // NOI18N
        areaTesto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(areaTesto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 772, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(areaTesto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane areaTesto;
    // End of variables declaration//GEN-END:variables

    

    


}
