
package it.difesa.esercito.rav17.infermeria.vista;

import it.difesa.esercito.rav17.infermeria.controllo.FinestraModelloGLController;
import it.quasar_x7.java.utile.DataOraria;

/**
 *
 * @author Dr Domenico della Peruta
 * @version 1.0.0 modifica 02/02/2016
 */
public class FinestraModelloGL extends javax.swing.JFrame {
    
    
    private FinestraModelloGLController gestore;
    
    
    public FinestraModelloGL(Object[] militare,DataOraria data,boolean verifica) {
        initComponents();
        gestore=new FinestraModelloGLController(this,data,militare,verifica);
    }

    public FinestraModelloGL(Object[] verbaleML) {
        initComponents();
        gestore=new FinestraModelloGLController(this,verbaleML);
        
    }

    public FinestraModelloGLController getGestore() {
        return gestore;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        pannelloNominativo = new javax.swing.JPanel();
        testoLuogo = new javax.swing.JTextField();
        luogoNascita = new javax.swing.JLabel();
        testoNome = new javax.swing.JTextField();
        testoCognome = new javax.swing.JTextField();
        testoGrado = new javax.swing.JTextField();
        dataNascita = new javax.swing.JLabel();
        cognome = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        grado = new javax.swing.JLabel();
        valoreGiornoNascita = new javax.swing.JFormattedTextField();
        valoreAnnoNascita = new javax.swing.JFormattedTextField();
        valoreMeseNascita = new javax.swing.JFormattedTextField();
        nome1 = new javax.swing.JLabel();
        testoReparto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rgt = new javax.swing.JLabel();
        incarico = new javax.swing.JLabel();
        testoIndirizzo = new javax.swing.JTextField();
        testoResidenza = new javax.swing.JTextField();
        incarico1 = new javax.swing.JLabel();
        testoIncarico = new javax.swing.JTextField();
        rgt2 = new javax.swing.JLabel();
        testoASL = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        pulsanteStampa2 = new javax.swing.JButton();
        pulsanteStampa1 = new javax.swing.JButton();
        pulsanteSalva = new javax.swing.JButton();
        selezionaMedico = new javax.swing.JComboBox();
        jPanel31 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        campoData = new it.quasar_x7.java.swing.componenti.CampoData();
        tabellaSchede = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dataFruizione = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        testoNumeroGiorni = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        testoElementiNonSanitari = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        selezionaRelazioneAllegata = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        selezionaProspettoConv = new javax.swing.JComboBox();
        selezionaDocMatricolare = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        testoAllegatoProspettoConv = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        testoAllegatoDocMatricolare = new javax.swing.JFormattedTextField();
        selezionaCertificatoAssenza = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        testoAllegatoselezionaCertificatoAssenza = new javax.swing.JFormattedTextField();
        pannelloTabella = new javax.swing.JPanel();
        pulsanteAggiungiCausaServ = new javax.swing.JButton();
        pulsanteEliminaCausaServ = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabellaCauseDiServizio = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        selezionaSuperamentoAssenza = new javax.swing.JCheckBox();
        selezionaTerminePeriodoAssenza = new javax.swing.JCheckBox();
        selezionaPersistenzaIdoneita = new javax.swing.JCheckBox();
        selezionaPresuntaPerditaIdoneita = new javax.swing.JCheckBox();
        selezionaAltreInabilita = new javax.swing.JCheckBox();
        selezionaCausaServizio = new javax.swing.JCheckBox();
        selezionaSuRichiesta = new javax.swing.JCheckBox();
        selezionaAltro = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        testoPeriodoAssenza = new javax.swing.JTextField();
        testoFormeInabilita = new javax.swing.JTextField();
        testoAltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        selezionaRiconosciutoTempNonIdoneo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        testoAltriElementiSanitari = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        testoAnamnesi = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        testoEsameObiettivo = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        testoGiudizioDiagnostico = new javax.swing.JTextArea();

        org.jdesktop.layout.GroupLayout jPanel12Layout = new org.jdesktop.layout.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        org.jdesktop.layout.GroupLayout jPanel17Layout = new org.jdesktop.layout.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 27, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finestra Modello GL");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pannelloNominativo.setBackground(new java.awt.Color(216, 234, 252));
        pannelloNominativo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MILITARE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N
        pannelloNominativo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pannelloNominativoMouseMoved(evt);
            }
        });

        testoLuogo.setEditable(false);
        testoLuogo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        luogoNascita.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        luogoNascita.setText("luogo di nascita");

        testoNome.setEditable(false);
        testoNome.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        testoCognome.setEditable(false);
        testoCognome.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        testoGrado.setEditable(false);
        testoGrado.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        dataNascita.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        dataNascita.setText("data di nascita");

        cognome.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cognome.setText("cognome");

        nome.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        nome.setText("nome");

        grado.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        grado.setText("grado");

        valoreGiornoNascita.setEditable(false);
        valoreGiornoNascita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        valoreAnnoNascita.setEditable(false);
        valoreAnnoNascita.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        valoreAnnoNascita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        valoreAnnoNascita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valoreAnnoNascitaActionPerformed(evt);
            }
        });

        valoreMeseNascita.setEditable(false);
        valoreMeseNascita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        nome1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        nome1.setText("reparto");

        testoReparto.setEditable(false);
        testoReparto.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        rgt.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rgt.setText("residenza");

        incarico.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        incarico.setText("indirizzo");

        testoIndirizzo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        testoResidenza.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        incarico1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        incarico1.setText("incarico");

        testoIncarico.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        rgt2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rgt2.setText("ASL");

        testoASL.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(incarico1)
                        .add(18, 18, 18)
                        .add(testoIncarico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rgt2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testoASL))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rgt)
                            .add(incarico))
                        .add(18, 18, 18)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(testoResidenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(testoIndirizzo))))
                .add(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(incarico1)
                    .add(testoIncarico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rgt2)
                    .add(testoASL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rgt)
                    .add(testoResidenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(incarico)
                    .add(testoIndirizzo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout pannelloNominativoLayout = new org.jdesktop.layout.GroupLayout(pannelloNominativo);
        pannelloNominativo.setLayout(pannelloNominativoLayout);
        pannelloNominativoLayout.setHorizontalGroup(
            pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pannelloNominativoLayout.createSequentialGroup()
                .addContainerGap()
                .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pannelloNominativoLayout.createSequentialGroup()
                        .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(grado)
                            .add(cognome))
                        .add(26, 26, 26)
                        .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pannelloNominativoLayout.createSequentialGroup()
                                .add(testoCognome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 68, Short.MAX_VALUE)
                                .add(nome))
                            .add(pannelloNominativoLayout.createSequentialGroup()
                                .add(testoGrado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(nome1)))
                        .add(0, 0, 0)
                        .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(testoNome)
                            .add(testoLuogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, testoReparto)))
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pannelloNominativoLayout.createSequentialGroup()
                        .add(dataNascita)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(valoreGiornoNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(valoreMeseNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(valoreAnnoNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(36, 36, 36)
                        .add(luogoNascita)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        pannelloNominativoLayout.setVerticalGroup(
            pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pannelloNominativoLayout.createSequentialGroup()
                .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(grado)
                    .add(testoGrado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nome1)
                    .add(testoReparto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cognome)
                    .add(testoCognome)
                    .add(nome)
                    .add(testoNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(pannelloNominativoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dataNascita)
                    .add(valoreGiornoNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(valoreMeseNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(luogoNascita)
                    .add(testoLuogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(valoreAnnoNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        pulsanteStampa2.setText("Stampa pag. 2");
        pulsanteStampa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteStampa2ActionPerformed(evt);
            }
        });

        pulsanteStampa1.setText("Stampa pag. 1");
        pulsanteStampa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteStampa1ActionPerformed(evt);
            }
        });

        pulsanteSalva.setText("Salva");
        pulsanteSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteSalvaActionPerformed(evt);
            }
        });

        selezionaMedico.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaMedico.setForeground(new java.awt.Color(0, 102, 102));

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(pulsanteSalva, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(selezionaMedico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pulsanteStampa1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pulsanteStampa2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(0, 5, Short.MAX_VALUE)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pulsanteStampa1)
                    .add(pulsanteStampa2)
                    .add(pulsanteSalva)
                    .add(selezionaMedico, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0))
        );

        jPanel31.setBackground(new java.awt.Color(0, 51, 255));

        jLabel24.setText("data");

        org.jdesktop.layout.GroupLayout jPanel31Layout = new org.jdesktop.layout.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel24)
                .add(18, 18, 18)
                .add(campoData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel31Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel24)
                    .add(campoData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabellaSchede.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("Ai fini della computo del periodo massimo di aspettativa fruibile nel quinquennio di valutazione,");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel9.setText("alla data del");

        dataFruizione.setDateFormatString("dd/MM/yyyy");
        dataFruizione.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel10.setText("ha fruito di gg");

        testoNumeroGiorni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        testoNumeroGiorni.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel11.setText("complessivi");

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel12.setText("Elementi informativi non sanitari:");

        testoElementiNonSanitari.setColumns(20);
        testoElementiNonSanitari.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        testoElementiNonSanitari.setRows(5);
        testoElementiNonSanitari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                testoElementiNonSanitariCaretUpdate(evt);
            }
        });
        jScrollPane8.setViewportView(testoElementiNonSanitari);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel13.setText("Relazione allegata:");

        selezionaRelazioneAllegata.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        selezionaRelazioneAllegata.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO", "SI" }));

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabel12)
                        .add(122, 122, 122)
                        .add(jLabel13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(selezionaRelazioneAllegata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(61, 61, 61))
                    .add(jScrollPane8))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(selezionaRelazioneAllegata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel14.setText("Prospetto assenze dal servizio per malatia/conv./inabilità");

        selezionaProspettoConv.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaProspettoConv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO", "SI" }));

        selezionaDocMatricolare.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaDocMatricolare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO", "SI" }));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel15.setText("Documento matricolare o equivalente");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel16.setText("Allegato n.");

        testoAllegatoProspettoConv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        testoAllegatoProspettoConv.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel17.setText("Allegato n.");

        testoAllegatoDocMatricolare.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        testoAllegatoDocMatricolare.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        selezionaCertificatoAssenza.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaCertificatoAssenza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO", "SI" }));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel18.setText("Copia certificazione sanitaria inerente l'assenza dal serv.");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel19.setText("Allegato n.");

        testoAllegatoselezionaCertificatoAssenza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        testoAllegatoselezionaCertificatoAssenza.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel15)
                    .add(jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(0, 0, 0)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(selezionaCertificatoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selezionaDocMatricolare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selezionaProspettoConv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel8Layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(testoAllegatoProspettoConv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel8Layout.createSequentialGroup()
                        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel17)
                            .add(jLabel19))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(testoAllegatoselezionaCertificatoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(testoAllegatoDocMatricolare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(0, 62, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel8Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selezionaProspettoConv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel16)
                    .add(testoAllegatoProspettoConv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(selezionaDocMatricolare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel17)
                    .add(testoAllegatoDocMatricolare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(selezionaCertificatoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19)
                    .add(testoAllegatoselezionaCertificatoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8)
                            .add(jPanel5Layout.createSequentialGroup()
                                .add(jLabel9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dataFruizione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel10)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(testoNumeroGiorni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel11)))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jLabel8)
                .add(0, 0, 0)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(dataFruizione, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel10)
                        .add(testoNumeroGiorni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel11))
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabellaSchede.addTab("SEZ. A -Amministrativa", jPanel5);

        pulsanteAggiungiCausaServ.setText("Aggiungi");
        pulsanteAggiungiCausaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteAggiungiCausaServActionPerformed(evt);
            }
        });

        pulsanteEliminaCausaServ.setText("Elimina");
        pulsanteEliminaCausaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteEliminaCausaServActionPerformed(evt);
            }
        });

        tabellaCauseDiServizio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        tabellaCauseDiServizio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Infermità o lesione", "Dipendenza", "Tempestività domanda", "P.V. Mod. o provvedimento definitivo", "datato", "C.M.2° Instanza o C.M.O. o Direttore o Aministrazione o Ente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabellaCauseDiServizio.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane9.setViewportView(tabellaCauseDiServizio);

        org.jdesktop.layout.GroupLayout pannelloTabellaLayout = new org.jdesktop.layout.GroupLayout(pannelloTabella);
        pannelloTabella.setLayout(pannelloTabellaLayout);
        pannelloTabellaLayout.setHorizontalGroup(
            pannelloTabellaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pannelloTabellaLayout.createSequentialGroup()
                .addContainerGap()
                .add(pannelloTabellaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 572, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pannelloTabellaLayout.createSequentialGroup()
                        .add(pulsanteAggiungiCausaServ)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pulsanteEliminaCausaServ)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannelloTabellaLayout.setVerticalGroup(
            pannelloTabellaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pannelloTabellaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pannelloTabellaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pulsanteAggiungiCausaServ)
                    .add(pulsanteEliminaCausaServ))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        tabellaSchede.addTab("SEZ. A - Causa Servizio", pannelloTabella);

        selezionaSuperamentoAssenza.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaSuperamentoAssenza.setText("per superamento del periodo di assenza dal servizio per convalescenza");
        selezionaSuperamentoAssenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaSuperamentoAssenzaActionPerformed(evt);
            }
        });

        selezionaTerminePeriodoAssenza.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaTerminePeriodoAssenza.setText("al termine di periodo di assenza");
        selezionaTerminePeriodoAssenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaTerminePeriodoAssenzaActionPerformed(evt);
            }
        });

        selezionaPersistenzaIdoneita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaPersistenzaIdoneita.setText("per dubbio sulla persistenza della idoneita' al servizio militare");
        selezionaPersistenzaIdoneita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaPersistenzaIdoneitaActionPerformed(evt);
            }
        });

        selezionaPresuntaPerditaIdoneita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaPresuntaPerditaIdoneita.setText("per condizione di salute che fanno presumere una permanente inabilita' al servizio militare");
        selezionaPresuntaPerditaIdoneita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaPresuntaPerditaIdoneitaActionPerformed(evt);
            }
        });

        selezionaAltreInabilita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaAltreInabilita.setText("per altre forme di inabilita'");
        selezionaAltreInabilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaAltreInabilitaActionPerformed(evt);
            }
        });

        selezionaCausaServizio.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaCausaServizio.setText("nell'ambito dell'accertamento di una dipendenza da causa di servizio e/o connessi benefici");
        selezionaCausaServizio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaCausaServizioActionPerformed(evt);
            }
        });

        selezionaSuRichiesta.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaSuRichiesta.setText("a richiesta dell'interessato sulla base di idonea certificazione sanitaria");
        selezionaSuRichiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaSuRichiestaActionPerformed(evt);
            }
        });

        selezionaAltro.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaAltro.setText("altro:");
        selezionaAltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selezionaAltroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setText("L'accertamento sanitario è richiesto in quanto sussiste la necessità di una verifica in ordine all'idoneità");

        testoPeriodoAssenza.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        testoPeriodoAssenza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoPeriodoAssenzaActionPerformed(evt);
            }
        });

        testoFormeInabilita.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        testoFormeInabilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoFormeInabilitaActionPerformed(evt);
            }
        });

        testoAltro.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        testoAltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testoAltroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel1.setText("In attesa della visita collegiale, l'interessato ");

        selezionaRiconosciutoTempNonIdoneo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        selezionaRiconosciutoTempNonIdoneo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NON" }));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel3.setText("è stato riconosciuto temporaneamente non idoneo al servizio");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setText("altri elementi informativi (sanitari)");

        testoAltriElementiSanitari.setColumns(20);
        testoAltriElementiSanitari.setRows(5);
        testoAltriElementiSanitari.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                testoAltriElementiSanitariCaretUpdate(evt);
            }
        });
        jScrollPane3.setViewportView(testoAltriElementiSanitari);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(selezionaSuperamentoAssenza, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 574, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jLabel2)
                                .add(selezionaPresuntaPerditaIdoneita)
                                .add(jPanel3Layout.createSequentialGroup()
                                    .add(selezionaAltreInabilita)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(testoFormeInabilita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 293, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(selezionaCausaServizio)
                                .add(selezionaSuRichiesta)
                                .add(jPanel3Layout.createSequentialGroup()
                                    .add(selezionaTerminePeriodoAssenza)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(testoPeriodoAssenza))
                                .add(selezionaPersistenzaIdoneita)
                                .add(jPanel3Layout.createSequentialGroup()
                                    .add(selezionaAltro)
                                    .add(18, 18, 18)
                                    .add(testoAltro))
                                .add(jPanel3Layout.createSequentialGroup()
                                    .add(jLabel1)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(selezionaRiconosciutoTempNonIdoneo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(jLabel3))))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap(96, Short.MAX_VALUE))
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel4)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jLabel2)
                .add(0, 0, 0)
                .add(selezionaSuperamentoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(testoPeriodoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selezionaTerminePeriodoAssenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(selezionaPersistenzaIdoneita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(selezionaPresuntaPerditaIdoneita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(testoFormeInabilita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selezionaAltreInabilita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(selezionaCausaServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(selezionaSuRichiesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(testoAltro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selezionaAltro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(selezionaRiconosciutoTempNonIdoneo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(0, 0, 0)
                .add(jLabel4)
                .add(0, 0, 0)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        tabellaSchede.addTab("SEZ. B - Accertamento", jScrollPane1);

        jLabel5.setText("Anamnesi");

        testoAnamnesi.setColumns(20);
        testoAnamnesi.setRows(5);
        testoAnamnesi.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                testoAnamnesiCaretUpdate(evt);
            }
        });
        jScrollPane5.setViewportView(testoAnamnesi);

        jLabel6.setText("Esame Obiettivo");

        testoEsameObiettivo.setColumns(20);
        testoEsameObiettivo.setRows(5);
        testoEsameObiettivo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                testoEsameObiettivoCaretUpdate(evt);
            }
        });
        jScrollPane6.setViewportView(testoEsameObiettivo);

        jLabel7.setText("Giudizio Diagnostico");

        testoGiudizioDiagnostico.setColumns(20);
        testoGiudizioDiagnostico.setRows(5);
        testoGiudizioDiagnostico.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                testoGiudizioDiagnosticoCaretUpdate(evt);
            }
        });
        jScrollPane7.setViewportView(testoGiudizioDiagnostico);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel5))
                            .add(jLabel6))
                        .add(42, 42, 42)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .add(jScrollPane6))))
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel4);

        tabellaSchede.addTab("SEZ. B - Giudizio", jScrollPane4);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(tabellaSchede, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(pannelloNominativo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(pannelloNominativo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(tabellaSchede, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 336, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(0, 0, 0))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valoreAnnoNascitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valoreAnnoNascitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valoreAnnoNascitaActionPerformed

    private void pannelloNominativoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pannelloNominativoMouseMoved
        
    }//GEN-LAST:event_pannelloNominativoMouseMoved

    private void pulsanteSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteSalvaActionPerformed
       gestore.pulsanteSalva(evt);
    }//GEN-LAST:event_pulsanteSalvaActionPerformed

    private void pulsanteStampa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteStampa1ActionPerformed
        gestore.pulsanteStampa(evt);
        
    }//GEN-LAST:event_pulsanteStampa1ActionPerformed

    private void selezionaSuperamentoAssenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaSuperamentoAssenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaSuperamentoAssenzaActionPerformed

    private void selezionaTerminePeriodoAssenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaTerminePeriodoAssenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaTerminePeriodoAssenzaActionPerformed

    private void selezionaPersistenzaIdoneitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaPersistenzaIdoneitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaPersistenzaIdoneitaActionPerformed

    private void selezionaPresuntaPerditaIdoneitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaPresuntaPerditaIdoneitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaPresuntaPerditaIdoneitaActionPerformed

    private void selezionaAltreInabilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaAltreInabilitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaAltreInabilitaActionPerformed

    private void selezionaCausaServizioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaCausaServizioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaCausaServizioActionPerformed

    private void selezionaSuRichiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaSuRichiestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaSuRichiestaActionPerformed

    private void selezionaAltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selezionaAltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selezionaAltroActionPerformed

    private void testoPeriodoAssenzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoPeriodoAssenzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoPeriodoAssenzaActionPerformed

    private void testoFormeInabilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoFormeInabilitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoFormeInabilitaActionPerformed

    private void testoAltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testoAltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testoAltroActionPerformed

    private void pulsanteAggiungiCausaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteAggiungiCausaServActionPerformed
        gestore.pulsanteAggiungi(evt);
        
    }//GEN-LAST:event_pulsanteAggiungiCausaServActionPerformed

    private void pulsanteEliminaCausaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteEliminaCausaServActionPerformed
        gestore.pulsanteElimina(evt);
        
    }//GEN-LAST:event_pulsanteEliminaCausaServActionPerformed

    private void pulsanteStampa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteStampa2ActionPerformed
        gestore.pulsanteStampa2Parte(evt);
             
                
    }//GEN-LAST:event_pulsanteStampa2ActionPerformed

    private void testoAnamnesiCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_testoAnamnesiCaretUpdate
        if(gestore != null)
            gestore.limite(evt,this.testoAnamnesi,500); 
    }//GEN-LAST:event_testoAnamnesiCaretUpdate

    private void testoEsameObiettivoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_testoEsameObiettivoCaretUpdate
        if(gestore != null)
            gestore.limite(evt,this.testoEsameObiettivo,500); 
    }//GEN-LAST:event_testoEsameObiettivoCaretUpdate

    private void testoGiudizioDiagnosticoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_testoGiudizioDiagnosticoCaretUpdate
        if(gestore != null)
            gestore.limite(evt,this.testoGiudizioDiagnostico,500); 
    }//GEN-LAST:event_testoGiudizioDiagnosticoCaretUpdate

    private void testoAltriElementiSanitariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_testoAltriElementiSanitariCaretUpdate
        if(gestore != null)
            gestore.limite(evt,this.testoAltriElementiSanitari,500); 
    }//GEN-LAST:event_testoAltriElementiSanitariCaretUpdate

    private void testoElementiNonSanitariCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_testoElementiNonSanitariCaretUpdate
        if(gestore != null)
            gestore.limite(evt,this.testoElementiNonSanitari,500); 
    }//GEN-LAST:event_testoElementiNonSanitariCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public it.quasar_x7.java.swing.componenti.CampoData campoData;
    private javax.swing.JLabel cognome;
    public com.toedter.calendar.JDateChooser dataFruizione;
    private javax.swing.JLabel dataNascita;
    private javax.swing.JLabel grado;
    private javax.swing.JLabel incarico;
    private javax.swing.JLabel incarico1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel luogoNascita;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nome1;
    private javax.swing.JPanel pannelloNominativo;
    private javax.swing.JPanel pannelloTabella;
    public javax.swing.JButton pulsanteAggiungiCausaServ;
    public javax.swing.JButton pulsanteEliminaCausaServ;
    public javax.swing.JButton pulsanteSalva;
    public javax.swing.JButton pulsanteStampa1;
    public javax.swing.JButton pulsanteStampa2;
    private javax.swing.JLabel rgt;
    private javax.swing.JLabel rgt2;
    public javax.swing.JCheckBox selezionaAltreInabilita;
    public javax.swing.JCheckBox selezionaAltro;
    public javax.swing.JCheckBox selezionaCausaServizio;
    public javax.swing.JComboBox selezionaCertificatoAssenza;
    public javax.swing.JComboBox selezionaDocMatricolare;
    public javax.swing.JComboBox selezionaMedico;
    public javax.swing.JCheckBox selezionaPersistenzaIdoneita;
    public javax.swing.JCheckBox selezionaPresuntaPerditaIdoneita;
    public javax.swing.JComboBox selezionaProspettoConv;
    public javax.swing.JComboBox selezionaRelazioneAllegata;
    public javax.swing.JComboBox selezionaRiconosciutoTempNonIdoneo;
    public javax.swing.JCheckBox selezionaSuRichiesta;
    public javax.swing.JCheckBox selezionaSuperamentoAssenza;
    public javax.swing.JCheckBox selezionaTerminePeriodoAssenza;
    public javax.swing.JTable tabellaCauseDiServizio;
    private javax.swing.JTabbedPane tabellaSchede;
    public javax.swing.JTextField testoASL;
    public javax.swing.JFormattedTextField testoAllegatoDocMatricolare;
    public javax.swing.JFormattedTextField testoAllegatoProspettoConv;
    public javax.swing.JFormattedTextField testoAllegatoselezionaCertificatoAssenza;
    public javax.swing.JTextArea testoAltriElementiSanitari;
    public javax.swing.JTextField testoAltro;
    public javax.swing.JTextArea testoAnamnesi;
    public javax.swing.JTextField testoCognome;
    public javax.swing.JTextArea testoElementiNonSanitari;
    public javax.swing.JTextArea testoEsameObiettivo;
    public javax.swing.JTextField testoFormeInabilita;
    public javax.swing.JTextArea testoGiudizioDiagnostico;
    public javax.swing.JTextField testoGrado;
    public javax.swing.JTextField testoIncarico;
    public javax.swing.JTextField testoIndirizzo;
    public javax.swing.JTextField testoLuogo;
    public javax.swing.JTextField testoNome;
    public javax.swing.JFormattedTextField testoNumeroGiorni;
    public javax.swing.JTextField testoPeriodoAssenza;
    public javax.swing.JTextField testoReparto;
    public javax.swing.JTextField testoResidenza;
    public javax.swing.JFormattedTextField valoreAnnoNascita;
    public javax.swing.JFormattedTextField valoreGiornoNascita;
    public javax.swing.JFormattedTextField valoreMeseNascita;
    // End of variables declaration//GEN-END:variables
}
