package it.quasar_x7.infermeria.vista;

import it.quasar_x7.infermeria.controllo.FinestraAttivitaMensiliController;



/**
 *
 * @author Dr Domenico della Peruta
 * @version 1.0.0 ultima modifica 20/04/2016
 */
public class FinestraAttivitaMensili extends javax.swing.JFrame {

    private final FinestraAttivitaMensiliController gestore;
    /**
     * Creates new form FinestraAttivitaMensili
     */
    public FinestraAttivitaMensili() {
        initComponents();
        gestore = new FinestraAttivitaMensiliController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        calendario = new javax.swing.JTable();
        selettoreAnno = new com.toedter.calendar.JYearChooser();
        pulsanteCercaMese = new javax.swing.JButton();
        seletoreMese = new com.toedter.calendar.JMonthChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        calendario.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(calendario);

        pulsanteCercaMese.setText("Cerca");
        pulsanteCercaMese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulsanteCercaMeseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(seletoreMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selettoreAnno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 660, Short.MAX_VALUE)
                .addComponent(pulsanteCercaMese, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pulsanteCercaMese)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seletoreMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selettoreAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 541, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pulsanteCercaMeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulsanteCercaMeseActionPerformed
        if(evt.getSource() instanceof javax.swing.JButton){
            gestore.creaCalendario();
        }
    }//GEN-LAST:event_pulsanteCercaMeseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable calendario;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JButton pulsanteCercaMese;
    public com.toedter.calendar.JMonthChooser seletoreMese;
    public com.toedter.calendar.JYearChooser selettoreAnno;
    // End of variables declaration//GEN-END:variables
}
